language: c

os: linux
dist: bionic

compiler:
 - clang
 - gcc

# Adapted from https://github.com/UnfoldedInc/deck.gl-native/blob/8efa577bcd8ebefbe8a6a996936efaa388a198e4/.travis.yml
install:
  # Install vcpkg and dependencies
  - pushd $HOME
  - if [ -d "$HOME/vcpkg/.git" ] ; then echo vcpkg cached ; VCPKG_CACHED=1 ; else rm -rf vcpkg ; git clone https://github.com/Microsoft/vcpkg ; fi
  - cd vcpkg
  - git checkout .
  - CURRENT_VCPKG_REV="$(git rev-parse HEAD)"
  - git pull
  - NEW_VCPKG_REV="$(git rev-parse HEAD)"
  # Avoid rebuilding vcpkg itself unless it was not cached, or an update has been pulled.
  - if [ "$VCPKG_CACHED" -a "$NEW_VCPKG_REV" == "$CURRENT_VCPKG_REV" ] ; then echo vcpkg bootstrap skipped ; else ./bootstrap-vcpkg.sh ; fi
  # Install our C++ dependencies:
  - ./vcpkg install sdl2 sdl2-mixer sdl2-ttf libpng zlib fltk --recurse
  - rm -rf buildtrees
  - popd

cache:
  directories:
    - ${VCPKG_ROOT}

before_script:
  # Build out of source
  - mkdir build
  - cd build
  - cmake -DCMAKE_TOOLCHAIN_FILE=${VCPKG_ROOT}/scripts/buildsystems/vcpkg.cmake ..

script:
  - make -j 2
